
以下のfunctionで
重複はあるかもしれないけど，
すべてのG-軌道をもれなくlist に含めているよね？

PSubgroupsModG:=function(A, G)
  #
  local IsGMinilal, Bgens, IsP, IsNew,
  task;
  #
  Bgens:=[ [] ];
  #
  IsP:=function(gens)
    #
    if (the group generated by gens has property P) then return(true); 
    else return(false);
    fi;
    #
  end;
  #
  IsGMinilal:=function(ss)
    local gg, ssg;
    for gg in G do 
      ssg:=List(ss, xx->Action(xx, gg));
      Sort(ssg);
      if ssg<ss then return(false); fi;
    od;
    return(true);
  end;
  #
  IsNew:=function(gens)
    local oldgens;
    for oldgens in Bgens do 
      if (the group generated by gens = the group generated by oldgens) then return(false); fi;
    od; 
    return(true);
  end;
  #
  IsInSubg:=function(aa, gens)
    if (aa is in the group generated by gens) then return(true); 
    else return(false);
    fi;
  end;
  #
  # IsLarger is a comparizon in A
  #
  task:=function(gens, leng)
    local newa, lastg;
    lastg:=gens[leng];
    for newa in A do 
      if newa in gens then continue; fi;
      if IsLarger(newa, lastg) and not IsInSubg(newa, gens) then 
        Add(gens, newa);
        if IsGMinimal(gens) and IsP(gens) then 
          if IsNew(gens) then 
            Add(Bgens, List(gens));
          fi;
          task(gens, leng+1);
        fi;
        if newa<>Remove(gens) then beep(69691); fi;
      fi;
    od;
  end;
  #
  task（[], 0)
  #
  return(Bgens);
end;
